### ISSUE TITLE
animation-direction "forwards" could be "normal"

### ISSUE THREAD

**Issue by danielabar** [ladieslearningcode/llc-interactive-stories-and-game-making#11]
This [line](https://github.com/ladieslearningcode/llc-interactive-stories-and-game-making/blob/master/project/reference/game03-action/styles.css#L34) in the action game sets `animation-direction` to `forwards`:

``` css
form {
  animation-name: move;
  animation-duration: 30s;
  animation-delay: 1s;
  animation-direction: forwards;
  animation-timing-function: linear;
}
```

But according to [MDN](https://developer.mozilla.org/en/docs/Web/CSS/animation-direction) I don't think that's a valid option. Instead it could be set to `normal`, or the line could be removed entirely because `normal` is the default setting.

Let me know if you'd like me to submit a PR to fix it.
